# Generated by Django 3.2.25 on 2025-03-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_generic_page', '0002_websitegenericpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitegenericpage',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Embed code for newsletter, video embeds or other media.', null=True),
        ),
    ]
