# Generated by Django 3.2.25 on 2025-03-04 08:53

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_generic_page', '0003_websitegenericpage_embed_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitegenericpage',
            name='copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
