# Generated by Django 3.2.11 on 2025-04-11 13:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('website_generic_page', '0004_alter_websitegenericpage_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTrusteesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('copy', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('trustees', wagtail.core.fields.StreamField([('trustee', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=True)), ('role', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bio', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic', 'ul', 'ol', 'link'], required=False))]))], blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
