databases:
  - engine: PG
    name: db
    version: "12"
domains:
  - domain: banmarchive.commonknowledge.dev
    type: PRIMARY
envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:nqAWJXElIRuXUIta/nm3SFIXDAAFRaY0:Fxf2ZZ+zc5G/Mym1dGkUiPwz/hJbD3HyAtWXzhOtWeQkrTX1g+ytZ3f/YHcpcNsnt7tST91Wav3VwILS0wPmfCswhW0Rqqwb3H+e9aBO7aE=]
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:UODShe2skLp0NgK9aOOCeYX2RlJpJSwM:/W+ErZde+9JjvwVUcEClCKFHa0JukYCZX27rJ48br+uXfaV/35DlyESGvuYThYPmglItC8mLLHl0UgY=]
  - key: MAILGUN_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:rWtVG/LT8IzgUhRORiFSHxvzgahml62Y:ssG1hhzZgGvvCTFcT8C2Exey5EgCRyYv3zbgfp0xAVNYwWu8nmBXs7MH+pvUOdBMw26EPumQjrPQI6N6AMjghbqs]
  - key: BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${_self.PUBLIC_URL}
  - key: AWS_S3_REGION_NAME
    scope: RUN_AND_BUILD_TIME
    value: ams3
  - key: AWS_STORAGE_BUCKET_NAME
    scope: RUN_AND_BUILD_TIME
    value: banmarchive
  - key: AWS_S3_ENDPOINT_URL
    scope: RUN_AND_BUILD_TIME
    value: https://ams3.digitaloceanspaces.com
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: OQPXF34TDQBI7HARX6DE
  - key: MEDIA_URL
    scope: RUN_AND_BUILD_TIME
    value: https://banmarchive.ams3.cdn.digitaloceanspaces.com/
  - key: MAILGUN_API_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.eu.mailgun.net/v3
  - key: MAILGUN_SENDER_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: commonknowledge.dev
  - key: WAGTAILTRANSFER_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:0a95ID76+70k1J3ovZgXX4XtntJPhBHn:DJwiZqoi11NbWJJffi11NUJD46T4CUalDyEyhwGhESxfTHFYNUOFwvS/ums=]
jobs:
  - dockerfile_path: .do/Dockerfile
    github:
      branch: deploys
      deploy_on_push: true
      repo: commonknowledge/banmarchive
    instance_count: 1
    instance_size_slug: basic-xs
    kind: PRE_DEPLOY
    name: release
    run_command: bash .bin/release.sh
name: banmarchive
region: ams
services:
  - dockerfile_path: .do/Dockerfile
    github:
      branch: deploys
      deploy_on_push: true
      repo: commonknowledge/banmarchive
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: server
    routes:
      - path: /
    run_command: gunicorn --worker-tmp-dir /dev/shm banmarchive.wsgi
static_sites:
  - github:
      branch: deploys
      deploy_on_push: true
      repo: commonknowledge/banmarchive
    name: staticfiles
    output_dir: artifacts/static
    routes:
      - path: /static
