# Generated by Django 3.2.11 on 2025-03-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_about', '0003_auto_20250224_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteaboutsectionpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
