# Generated by Django 3.2.11 on 2025-02-28 15:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_news', '0004_websitenewsindexpage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitenewspage',
            name='embed_html',
            field=wagtail.core.fields.StreamField([('html', wagtail.core.blocks.RawHTMLBlock(help_text='Be careful when using custom embeds. They might break the page if not inserted correctly.'))], blank=True),
        ),
    ]
