# Generated by Django 3.2.25 on 2025-03-04 08:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_news', '0005_auto_20250302_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitenewspage',
            name='embed_html',
            field=wagtail.core.fields.StreamField([('html', wagtail.core.blocks.RawHTMLBlock(help_text='Be careful when using custom embeds. They might break the page if not inserted correctly.'))], blank=True),
        ),
    ]
