# Generated by Django 3.2.11 on 2025-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_news', '0006_websitenewspage_embed_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitenewspage',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
