# Generated by Django 3.2.3 on 2021-06-22 16:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_articlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('side_images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('pull_quote', wagtail.core.blocks.TextBlock(template='home/blocks/pull_quote.html'))]),
        ),
    ]
