# Generated by Django 3.2.25 on 2025-02-11 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAwardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', models.TextField(blank=True, null=True)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('organisation', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=12, null=True, verbose_name='Year awarded')),
                ('amount_awarded', models.FloatField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('award_type', models.CharField(blank=True, choices=[('standard', 'Standard Award'), ('ninafishman', 'Nina Fishman Translation Award'), ('major', 'Major Award')], max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WebsiteAwardsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
