# Generated by Django 3.2.25 on 2025-03-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_awards', '0003_websiteawardsindexpage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteawardssearch',
            name='copy',
        ),
    ]
