# Generated by Django 3.2.11 on 2025-03-03 12:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_awards', '0004_remove_websiteawardssearch_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteawardpage',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
