# Generated by Django 3.2.3 on 2021-06-03 16:29

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='introduction_author',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='introduction_content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='introduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
