# Generated by Django 3.2.3 on 2021-06-03 17:28

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20210603_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiarticleissue',
            name='issue_cover',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiarticleissue',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='simpleissue',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
