# Generated by Django 3.2.3 on 2021-06-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20210603_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='multiarticleissue',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiarticleissue',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiarticleissue',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleissue',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleissue',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleissue',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
