# Generated by Django 3.2.3 on 2021-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20210604_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
