# Generated by Django 3.2.3 on 2021-06-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20210604_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simpleissue',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
