# Generated by Django 3.2.3 on 2021-06-22 14:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20210622_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='short_introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
