# Generated by Django 3.2.3 on 2021-06-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_articlepage_content'),
        ('publications', '0010_publication_short_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='introduction_article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduction_for_publication', to='home.articlepage'),
        ),
    ]
