# Generated by Django 3.2.3 on 2021-08-02 17:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publications', '0011_alter_publication_introduction_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='publications.article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications_articletag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='multiarticleissue',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='simpleissue',
            name='tags',
        ),
        migrations.AlterField(
            model_name='multiarticleissue',
            name='issue_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document'),
        ),
        migrations.DeleteModel(
            name='PageTag',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='publications.ArticleTag', to='taggit.Tag', verbose_name='Keywords'),
        ),
    ]
