# Generated by Django 3.2.3 on 2022-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_auto_20210924_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='simpleissue',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
