# Generated by Django 3.2.25 on 2025-02-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('website_home', '0002_alter_websitehomepage_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitehomepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
