# Generated by Django 3.2.25 on 2025-03-11 08:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_home', '0003_websitehomepage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitehomepage',
            name='teasers',
            field=wagtail.core.fields.StreamField([('teaser', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock()), ('call_to_action', wagtail.core.blocks.CharBlock())]))], blank=True),
        ),
    ]
