# Generated by Django 3.2.11 on 2025-03-18 08:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website_home', '0005_alter_websitehomepage_teasers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitehomepage',
            name='teasers',
            field=wagtail.core.fields.StreamField([('teaser', wagtail.core.blocks.StructBlock([('label', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.URLBlock(required=False)), ('call_to_action', wagtail.core.blocks.CharBlock()), ('highlighted', wagtail.core.blocks.BooleanBlock(default=False, required=False))]))], blank=True),
        ),
    ]
