# Generated by Django 3.2.3 on 2021-07-01 13:19

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField(default=list)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page')),
            ],
        ),
        migrations.AddIndex(
            model_name='advancedsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='search_adva_keyword_bac0fd_gin'),
        ),
    ]
