# Generated by Django 3.2.3 on 2021-07-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordExtractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('tfidf_transformer', models.BinaryField(blank=True, null=True)),
                ('cv', models.BinaryField(blank=True, null=True)),
                ('stopwords', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=list)),
            ],
        ),
    ]
