# Generated by Django 3.2.3 on 2021-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_keywordextractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordextractor',
            name='kw_count_article',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='keywordextractor',
            name='kw_count_title',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='keywordextractor',
            name='max_df',
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name='keywordextractor',
            name='max_features',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='keywordextractor',
            name='ngram_max',
            field=models.IntegerField(default=3),
        ),
    ]
