# Generated by Django 3.2.3 on 2021-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210708_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordextractor',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordextractor',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
