# Generated by Django 3.2.3 on 2021-09-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210713_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeywordExtractor',
        ),
    ]
