# Generated by Django 3.2.3 on 2021-10-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_delete_keywordextractor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advancedsearchindex',
            index=models.Index(fields=['page_id'], name='search_adva_page_id_88aa71_idx'),
        ),
    ]
