name: Deploy to digitalocean
on:
  push:
    branches:
      - main

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Setup Git configuration
        run: |
          git config user.name "Deploy Bot"
          git config user.email "<>"

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/banmarchive:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Write out artifacts
        run: |
          git fetch origin deploys
          git checkout deploys
          echo "FROM ghcr.io/${{ github.repository_owner }}/banmarchive:${{ github.sha }}" > .do/Dockerfile
          mkdir -p artifacts
          docker run --user=0 --mount type=bind,src=$(pwd)/artifacts,dst=/app/artifacts --entrypoint=/bin/cp "ghcr.io/${{ github.repository_owner }}/banmarchive:${{ github.sha }}" -r static artifacts
          touch requirements.txt
          touch Aptfile
          git add -A
          git commit -m "Deploy ${{ github.sha }}"
          git push origin deploys

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        if: always()
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
